/* Testes de regressão — confirmam que as decisões do PATCH NOTES.md (secção "Decisões fixas") continuam a valer.
   Correr antes de cada push:  NODE_PATH=$(npm root -g) node tests/regressao.cjs
   Precisa do Playwright (global). Usa só dados fictícios (tests/fixtures) — nunca pôr extratos/recibos reais no repositório. */
const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path');
const PUB=path.join(__dirname,'..','public'),FX=path.join(__dirname,'fixtures');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json'};
const srv=http.createServer((q,r)=>{const f=path.join(PUB,decodeURIComponent(q.url.split('?')[0]).replace(/^\/$/,'/index.html'));
  fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);r.end();return}r.writeHead(200,{'content-type':MIME[path.extname(f)]||'application/octet-stream'});r.end(d)})});
let ok=0,falhas=[];
const t=(id,nome,cond,info)=>{if(cond){ok++;console.log(`  ✓ ${id} ${nome}`)}else{falhas.push(`${id} ${nome}`);console.log(`  ✗ ${id} ${nome}${info!==undefined?' → '+JSON.stringify(info):''}`)}};
(async()=>{
  await new Promise(r=>srv.listen(0,r));const U=`http://localhost:${srv.address().port}`;
  const b=await chromium.launch();const p=await b.newPage({viewport:{width:1500,height:900}});const erros=[];
  p.on('pageerror',e=>erros.push(e.message));p.on('dialog',d=>d.accept('Cartão refeição'));
  await p.route(/cdn\.jsdelivr\.net/,r=>r.abort()); // sem login nos testes
  await p.goto(U+'/financas.html');await p.evaluate(()=>localStorage.clear());await p.reload();
  const ev=(f,a)=>p.evaluate(f,a);const go=async tab=>{await ev(`document.querySelector('[data-tab="${tab}"]').click()`)};

  console.log('Extratos');
  await go('ext');
  await p.setInputFiles('#fExt',path.join(FX,'cgd_teste.csv'));await p.waitForTimeout(400);
  await p.selectOption('#bankSel','__cartao');await p.setInputFiles('#fExt',path.join(FX,'cartao_teste.csv'));await p.waitForTimeout(400);await p.selectOption('#bankSel','');
  const M=await ev(()=>DB.mov.map(m=>({d:m.desc,det:m.det,c:m.cat,r:m.ref,b:m.banco,v:m.valor,src:m.catSrc})));
  t('D01','importa CGD + cartão (6+3 movimentos)',M.length===9,M.length);
  t('D02','"Compra" sai da descrição e vai para Detalhes',!M.some(m=>/^compra\b/i.test(m.d))&&M.filter(m=>/Compra/.test(m.det)).length>=3,M.map(m=>m.d));
  t('D03','regras aplicadas ao importar (CONTINENTE → Supermercado)',M.find(m=>m.d.startsWith('CONTINENTE')).r==='Supermercado');
  await p.setInputFiles('#fExt',path.join(FX,'cgd_teste.csv'));await p.waitForTimeout(300);
  t('D04','reimportar não duplica',await ev(()=>DB.mov.length)===9);
  t('D05','"Por categorizar" = sem categoria OU sem referência',await ev(()=>{const m=DB.mov.find(x=>x.desc.startsWith('LOJA SEM'));m.cat='Outros';m.ref='';return isUnc(m)}));
  t('D06','trocas entre contas / levantamentos / Poupanças não contam como entrada/saída',await ev(()=>isInterna({cat:'Banco',ref:'Troca entre contas'})&&isInterna({cat:'Banco',ref:'Levantamentos'})&&isInterna({cat:'Poupanças',ref:'Férias'})));
  await go('ext');
  t('D08','dropdowns Categoria/Referência com largura fixa + "Limpar filtros"',await ev(()=>{const a=document.querySelector('#fCat').offsetWidth,b=document.querySelector('#fRef').offsetWidth;document.querySelector('#fCat').value='Alimentação';render();return a===document.querySelector('#fCat').offsetWidth&&b===document.querySelector('#fRef').offsetWidth&&!!document.querySelector('#btLimpaF')}));
  await ev(()=>{document.querySelector('#btLimpaF').click()});
  t('D09','"Limpar filtros" limpa pesquisa e filtros',await ev(()=>['#fQ','#fCat','#fRef','#fBanco'].every(q=>!document.querySelector(q).value)));
  t('D07','filtros e títulos da tabela de movimentos existem (fQ, fCat, fRef)',await ev(()=>!!(document.querySelector('#extBar #fQ')&&document.querySelector('#extBar #fRef')&&document.querySelector('#extHead thead'))));

  console.log('Despesas');
  t('D10','categorias fora das contas incluem Banco, Por tratar, Investimentos, Empresas, Rendimentos, Poupanças',await ev(()=>['Banco','Por tratar','Investimentos','Empresas','Rendimentos','Poupanças'].every(eFora)));
  t('D11','categoria Poupanças e Rendimentos existem',await ev(()=>['Poupanças','Rendimentos'].every(n=>DB.cats.some(c=>c.nome===n))));
  await ev(()=>{espSo().refs.push('Lazer›Jogos');aplicaRegras();render()});
  t('D12','referência "Só este movimento" não é usada pelas regras',await ev(()=>!DB.mov.some(m=>m.ref==='Jogos'&&m.catSrc==='regra')));
  await go('des');await p.click('#perMode [data-m="ano"]');await p.waitForTimeout(200);
  t('D13','Despesas: grelha de 12 meses (Mês e Ano iguais), com Total, Média e Previsão, e tabela das categorias fora das contas alinhada com a de cima',await ev(()=>{const t=document.querySelectorAll('#desCats table.dgrid');if(t.length!==2)return false;const h=[...t[0].querySelectorAll('thead th')].map(x=>x.textContent.trim());const h2=[...t[1].querySelectorAll('thead th')].map(x=>x.textContent.trim());return h.length===16&&h[13]==='Total'&&h[14]==='Média'&&h[15]==='Previsão'&&h2.length===16&&!h2.includes('Previsão')&&[...t[0].querySelectorAll('col')].map(c=>c.style.width).join()===[...t[1].querySelectorAll('col')].map(c=>c.style.width).join()}));
  t('D14','vista Ano: fora das contas numa linha por categoria (entradas − saídas), sem coluna "Entradas ano"',await ev(()=>!/Entradas ano/.test(document.querySelector('#desCats').innerText)&&/entradas − saídas/.test(document.querySelector('#desCats').innerText)));
  await p.click('#perMode [data-m="mes"]');

  console.log('Rendimentos');
  await ev(()=>{P.d=new Date(2026,8,1);perLabel()});await go('ren');
  await p.click('[data-dd="ddRend"]');await p.click('[data-radd2]');await p.click('#rdTipo [data-t="pon"]');await p.fill('#rdEnt','DEMO EMPRESA');await p.fill('#rdDesc','Teste');await p.fill('#rdData','2026-09-14');await p.fill('#rdBruto','850');await p.click('#rdOk');await p.waitForTimeout(200);
  const lig=await ev(()=>{const m=DB.mov.find(x=>x.desc.startsWith('TRF DEMO'));return [m.cat,m.catSrc]});
  t('D20','rendimento liga-se sozinho ao movimento com o mesmo valor → categoria Rendimentos',lig[0]==='Rendimentos'&&lig[1]==='rend',lig);
  t('D21','um só botão "Adicionar rendimento"',await ev(()=>document.querySelectorAll('[data-radd2]').length===1));
  await go('ext');await p.fill('#fQ','TRANSFER');await p.waitForTimeout(150);
  t('D22','subsídio no cartão é procurado só na conta Cartão refeição',await ev(()=>{const r={tipo:'rec',data:'2026-09-01',mes:'2026-09',liquido:150,vale:150,lk:{},lkMan:{}};return candidatos(r,'v').every(m=>m.banco===CARTAO)&&candidatos(r,'t').every(m=>m.banco!==CARTAO)}));
  await p.fill('#fQ','');

  console.log('Reembolsos');
  await ev(()=>{DB.mov.push({id:'mRb',k:'rbteste',man:true,banco:'Dinheiro',conta:'',dm:'2026-09-21',dv:'2026-09-21',desc:'DEVOLUCAO AMIGO',valor:20,saldo:null,cat:'',ref:'',catSrc:'',det:'',obs:'',quem:'',ord:0});P.m='mes';P.d=new Date(2026,8,1);perLabel();render()});
  await go('ext');await p.fill('#fQ','DEVOLUCAO');await p.waitForTimeout(150);
  await p.click('#extTable [data-reemb="mRb"]');await p.waitForTimeout(150);
  const cont=await ev(()=>DB.mov.find(x=>x.desc.startsWith('CONTINENTE')).id);
  await p.click(`#rbList [data-rbsel="${cont}"]`);await p.waitForTimeout(150);await p.fill('#fQ','');
  const rb=await ev(()=>{const m=DB.mov.find(x=>x.id==='mRb');return [m.cat,m.ref,!!m.reemb]});
  t('D16','atalho ↩ dá ao reembolso a categoria/referência da despesa original',rb[0]==='Alimentação'&&rb[1]==='Supermercado'&&rb[2],rb);
  t('D15','entrada em categoria de despesa = reembolso: abate às saídas e não conta como entrada',await ev(()=>eReemb(DB.mov.find(x=>x.id==='mRb'))&&!eReemb({valor:50,cat:'Rendimentos'})&&!eReemb({valor:50,cat:''})));
  await go('des');
  const d17=await ev(()=>{document.querySelector('[data-tab="des"]').click();const [a,b]=range(),sa=-DB.mov.filter(m=>m.dm>=a&&m.dm<=b&&m.cat==='Alimentação'&&m.valor<0).reduce((s,m)=>s+m.valor,0),esp=E(sa-20),k=a.slice(0,7);
    const ms=mesesGrelha(),i=ms.indexOf(k),tr=document.querySelector('#desCats tr.gc[data-dtog="Alimentação"]'),txt=tr?tr.children[i+1].textContent:'';return {ok:txt===esp,esp,txt}});
  t('D17','Despesas: saídas (total) = saídas − reembolsos',d17.ok,d17);

  console.log('Dividir');
  await go('ext');await p.fill('#fQ','NETFLIX');await p.waitForTimeout(150);
  const nid=await ev(()=>DB.mov.find(x=>x.desc.startsWith('NETFLIX')).id);
  await p.click(`#extTable [data-split="${nid}"]`);await p.waitForTimeout(150);
  await p.selectOption('#spRows tr:nth-child(1) [data-spc]','Lazer');await p.selectOption('#spRows tr:nth-child(1) [data-spr]','Jogos');
  await p.fill('#spRows tr:nth-child(2) [data-spv]','20');
  t('D18a','dividir só guarda quando a soma bate com o valor original',await ev(()=>document.querySelector('#spOk').disabled));
  await p.fill('#spRows tr:nth-child(2) [data-spv]','3,99');
  t('D48','ao dividir, a 1.ª linha é fechada e vale o original − as outras linhas',await ev(()=>{const i=document.querySelector('#spRows tr:nth-child(1) [data-spv]');return i.readOnly&&i.value==='10,00'&&!document.querySelector('#spOk').disabled}));await p.selectOption('#spRows tr:nth-child(2) [data-spc]','Casa');await p.selectOption('#spRows tr:nth-child(2) [data-spr]','Internet');
  await p.click('#spOk');await p.waitForTimeout(150);
  const sp=await ev(()=>{const m=DB.mov.find(x=>x.desc.startsWith('NETFLIX'));const x=expande([m]);return {n:m.partes.length,soma:r2(x.reduce((s,y)=>s+y.valor,0)),cats:x.map(y=>y.cat),sub:document.querySelectorAll('#extTable tr.parte').length}});
  t('D49','linhas divididas minimizadas por defeito',sp.sub===0,sp);
  await p.click(`#extTable [data-sptog="${nid}"]`);await p.waitForTimeout(100);
  sp.sub=await ev(()=>document.querySelectorAll('#extTable tr.parte').length);
  t('D18','movimento dividido: partes somam o original, contam nas categorias e aparecem como sub-linhas',sp.n===2&&sp.soma===-13.99&&sp.cats.join()==='Lazer,Casa'&&sp.sub===2,sp);
  await ev(()=>{DB.mov.push({id:'mRb2',k:'rbteste2',man:true,banco:'Dinheiro',conta:'',dm:'2026-09-22',dv:'2026-09-22',desc:'DEVOLVE INTERNET',valor:2,saldo:null,cat:'',ref:'',catSrc:'',det:'',obs:'',quem:'',ord:0});render()});
  await p.fill('#fQ','DEVOLVE INTERNET');await p.waitForTimeout(150);
  await p.click('#extTable [data-reemb="mRb2"]');await p.waitForTimeout(150);await p.click('#rbTodas');await p.waitForTimeout(100);
  await p.click(`#rbList [data-rbsel="${nid}#1"]`);await p.waitForTimeout(150);
  const rp=await ev(n=>{const m=DB.mov.find(x=>x.id==='mRb2'),o=DB.mov.find(x=>x.id===n);return {ok:m.reemb===chaveParte(o,1)&&m.cat==='Casa'&&m.ref==='Internet'&&/Reembolso de NETFLIX/.test(document.querySelector('#extTable tr[data-id="mRb2"]').children[6].textContent),cat:m.cat,r:m.reemb}},nid);
  t('D50','reembolso pode ligar a uma linha de um movimento dividido',rp.ok,rp);
  await ev(()=>{DB.mov.push({id:'mRb3',k:'rbteste3',man:true,banco:'Dinheiro',conta:'',dm:'2026-09-23',dv:'2026-09-23',desc:'TRF RECEBIDA GRUPO',valor:30,saldo:null,cat:'',ref:'',catSrc:'',det:'',obs:'',quem:'',ord:0});render()});
  await p.fill('#fQ','TRF RECEBIDA GRUPO');await p.waitForTimeout(150);
  await p.click('#extTable [data-split="mRb3"]');await p.waitForTimeout(150);
  await p.fill('#spRows tr:nth-child(2) [data-spv]','10');
  const d53=await ev(()=>({txt:document.querySelector('#spSoma').textContent,foot:!!document.querySelector('#spFoot #spAdd'),info:!!document.querySelector('#spInfo')&&!/Divida/.test(document.querySelector('#spDesc').textContent)}));
  t('D53','Dividir: sem texto "bate certo", ＋ Linha por baixo do valor e ajuda no ⓘ',d53.txt===''&&d53.foot&&d53.info,d53);
  await p.click('#spRows tr:nth-child(2) [data-spreemb]');await p.waitForTimeout(150);await p.click('#rbTodas');await p.waitForTimeout(100);
  await p.click(`#rbList [data-rbsel="${cont}"]`);await p.waitForTimeout(150);
  await p.click('#spOk');await p.waitForTimeout(150);
  const d54a=await ev(()=>{const m=DB.mov.find(x=>x.id==='mRb3');return {ok:m.partes.length===2&&!!m.partes[1].reemb&&m.partes[1].cat==='Alimentação'&&eReemb(expande([m])[1]),p:m.partes}});
  await p.click('#extTable [data-sptog="mRb3"]');await p.waitForTimeout(100);
  await p.click('#extTable [data-reembp="mRb3#0"]');await p.waitForTimeout(150);await p.click('#rbTodas');await p.waitForTimeout(100);
  await p.click(`#rbList [data-rbsel="${cont}"]`);await p.waitForTimeout(150);
  const d54b=await ev(()=>{const m=DB.mov.find(x=>x.id==='mRb3');return !!m.partes[0].reemb&&document.querySelectorAll('#extTable tr.parte [data-golk]').length===2});
  t('D54','entrada dividida: cada linha pode ser reembolso (↩ na janela Dividir e nas sub-linhas)',d54a.ok&&d54b,{d54a,d54b});
  const d55=await ev(()=>{const rs=[...document.querySelectorAll('#extTable tbody tr[data-id]')];const all=[...DB.mov];document.querySelector('#fQ').value='';render();const rows=[...document.querySelectorAll('#extTable tbody tr[data-id]')];const pos=rows.map(tr=>[...tr.querySelectorAll('td.acts .sl')].map(s=>Math.round(s.getBoundingClientRect().left-tr.getBoundingClientRect().left)).join(','));return {ok:rows.length>1&&new Set(pos).size===1&&pos[0].split(',').length===4,pos:[...new Set(pos)]}});
  t('D55','botões do fim da linha em posições fixas (4 lugares)',d55.ok,d55);
  await p.fill('#fQ','');
  t('D19','reembolso mostra só a ligação nos Detalhes',await ev(()=>{render();const tr=document.querySelector('#extTable tr[data-id="mRb"]');return !tr||(/Reembolso de/.test(tr.children[6].textContent)&&!/Diversos|COMPRAS/.test(tr.children[6].textContent))}));

  console.log('Pesquisa por data / calendário / pessoas');
  const dq=await ev(()=>{const m=DB.mov.find(x=>!x.man),d=m.dm.split('-');const q1=`${d[2]}/${d[1]}/${d[0]}`,q2=`${d[1]}/${d[0]}`;
    const f=q=>{document.querySelector('#fQ').value=q;render();return [...document.querySelectorAll('#extTable tbody tr[data-id]')].map(tr=>DB.mov.find(x=>x.id===tr.dataset.id))};
    const r1=f(q1),r2=f(q2),r3=f(`${d[2]}/${d[1]}`);document.querySelector('#fQ').value='';render();
    return {ok:r1.length>0&&r1.every(x=>x.dm===m.dm||x.dv===m.dm)&&r2.length>=r1.length&&r2.every(x=>x.dm.slice(0,7)===m.dm.slice(0,7)||x.dv.slice(0,7)===m.dm.slice(0,7))&&r3.length>=r1.length,n:[r1.length,r2.length,r3.length]}});
  t('D47','pesquisa dos Extratos aceita datas (dd/mm, dd/mm/aaaa, mm/aaaa)',dq.ok,dq);
  const cal=await ev(()=>{P.m='mes';P.d=new Date(2026,8,1);perLabel();document.querySelector('#perLbl').click();const pop=document.querySelector('#calPop');const vis=!pop.hidden&&pop.querySelectorAll('[data-cmes]').length===12;
    pop.querySelector('[data-cy="-1"]').click();pop.querySelector('[data-cmes="2"]').click();const a=P.m==='mes'&&P.d.getFullYear()===2025&&P.d.getMonth()===2&&pop.hidden;
    document.querySelector('#perLbl').click();pop.querySelector('[data-cano]').click();const b=P.m==='ano'&&P.d.getFullYear()===2025;
    P.m='mes';P.d=new Date(2026,8,1);document.querySelectorAll('#perMode button').forEach(x=>x.classList.toggle('on',x.dataset.m==='mes'));perLabel();render();return {ok:vis&&a&&b,vis,a,b}});
  t('D52','clicar na data abre calendário (ano + 12 meses) para escolher mês ou ano',cal.ok,cal);
  t('D51','janela Pessoas com pesquisa fixa que filtra as listas',await ev(()=>{document.querySelector('#btRegras').click();document.querySelector('#mRegras [data-mtab="mPessoas"]').click();const q=document.querySelector('#pesQ');const st=getComputedStyle(document.querySelector('#pesQw')).position;q.value='zzzqqq';q.dispatchEvent(new Event('input'));const n=document.querySelectorAll('#pesPend tbody tr,#pesList tbody tr').length;q.value='';q.dispatchEvent(new Event('input'));document.querySelector('#mPessoas').hidden=true;return st==='sticky'&&n===0}));

  console.log('Janelas e botões (v0.7r)');
  t('D55b','botões da linha pela ordem ↩ ✂ ✏ 🗑, encostados à direita',await ev(()=>{const tr=[...document.querySelectorAll('#extTable tbody tr[data-id]')].find(r=>r.querySelector('[data-edit]'))||document.querySelector('#extTable tbody tr[data-id]');const sl=[...tr.querySelectorAll('td.acts .sl')];const td=tr.querySelector('td.acts');return sl.length===4&&(!sl[1].firstChild||sl[1].querySelector('[data-split]'))&&sl[3].querySelector('[data-del]')&&getComputedStyle(td).textAlign==='right'}));
  t('D56','filtros: tipo (entradas/saídas) logo a seguir à pesquisa e banco no fim',await ev(()=>{const ids=[...document.querySelectorAll('#extBar .filt select,#extBar .filt .ms')].map(x=>x.id);return ids[0]==='fTipo'&&ids[ids.length-1]==='fBanco'}));
  t('D57a','um só botão "Regras e pessoas" com duas abas',await ev(()=>{if(document.querySelector('#btPessoas'))return false;document.querySelector('#btRegras').click();const a=!document.querySelector('#mRegras').hidden;document.querySelector('#mRegras [data-mtab="mPessoas"]').click();const b=document.querySelector('#mRegras').hidden&&!document.querySelector('#mPessoas').hidden;document.querySelector('#mPessoas [data-mtab="mRegras"]').click();const c=!document.querySelector('#mRegras').hidden;document.querySelector('#mRegras').hidden=true;return a&&b&&c}));
  t('D57b','um só botão Importar/Exportar com menu por baixo (Exportar | Importações)',await ev(()=>{if(document.querySelector('#btExp')||document.querySelector('#btImps'))return false;document.querySelector('#btIE').click();const a=!document.querySelector('#ddIE').hidden;document.querySelector('#ieImps').click();const b=document.querySelector('#ddIE').hidden&&!document.querySelector('#mImps').hidden;document.querySelector('#mImps').hidden=true;return a&&b}));
  await ev(()=>{document.querySelector('#fQ').value='';render()});
  const d60=await ev(()=>{const m=DB.mov.find(x=>x.desc.startsWith('CONTINENTE')),k=chave(m),n=DB.mov.length;apaga([m]);render();
    document.querySelector('#btMov').click();document.querySelector('#mMov [data-mtab="mElim"]').click();const lst=!document.querySelector('#mElim').hidden&&!!document.querySelector(`#elimList [data-repor]`);
    return {lst,k,n,gone:DB.mov.length===n-1,bloq:DB.del.includes(k)}});
  await p.setInputFiles('#fExt',path.join(FX,'cgd_teste.csv'));await p.waitForTimeout(300);
  const d60b=await ev(k=>{const naoVolta=!DB.mov.some(x=>chave(x)===k);document.querySelector('#elimList [data-repor]').click();const volta=DB.mov.some(x=>chave(x)===k)&&!(DB.delM||[]).some(x=>chave(x.m)===k);document.querySelector('#mElim').hidden=true;
    const j=junta(JSON.parse(JSON.stringify(DB)),{...JSON.parse(JSON.stringify(DB)),del:[...DB.del,k],rep:{}});return {naoVolta,volta,sync:j.d.mov.some(x=>chave(x)===k)}},d60.k);
  t('D58','movimentos eliminados: não voltam ao reimportar, aparecem em ＋ Movimento › Eliminados e podem ser repostos',d60.lst&&d60.gone&&d60.bloq&&d60b.naoVolta&&d60b.volta&&d60b.sync,{d60,d60b});
  const d61=await ev(()=>{const m=document.querySelector('#mRegras');m.hidden=false;const sh=m.querySelector('.sheet');sh.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));m.dispatchEvent(new MouseEvent('click',{bubbles:true}));const a=!m.hidden;m.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));m.dispatchEvent(new MouseEvent('click',{bubbles:true}));return {a,b:m.hidden}});
  t('D59','janelas fecham ao clicar fora, mas não ao carregar dentro e largar fora',d61.a&&d61.b,d61);
  t('D60','Dividir: ⓘ mostra a explicação numa etiqueta (não na caixa)',await ev(()=>{abreSplit(DB.mov.find(x=>x.valor<0));const b=document.querySelector('#spAjuda');const h0=b.hidden;document.querySelector('#spInfo').click();const ok=h0&&!b.hidden&&!!b.closest('.mh')&&document.querySelector('#spInfo').title==='Como funciona';document.querySelector('#mSplit').hidden=true;SP=null;return ok}));

  console.log('v0.7s');
  const x61=await ev(()=>{P.m='mes';P.d=new Date(2026,8,1);perLabel();document.querySelector('[data-tab="des"]').click();render();
    const cats=[...document.querySelectorAll('#desCats table.dgrid')[0].querySelectorAll('tr.gc')],abertas=cats.every(tr=>tr.classList.contains('open')),msel=document.querySelectorAll('#desCats table.dgrid')[0].querySelectorAll('thead th.msel').length===1&&/SET\/26/.test(document.querySelector('#desCats thead th.msel').textContent);
    const k=[...document.querySelectorAll('#desKpis .kpi .l')].map(x=>x.textContent);
    const g=document.querySelector('#desCats tr.gc');g.click();const fechou=!document.querySelector('#desCats tr.gc').classList.contains('open');document.querySelector('#desCats tr.gc').click();
    const ok0=!document.querySelector('#desCats input.pv')&&!!document.querySelector('#desCats tr.gr .pvro');
    const cc=[...document.querySelectorAll('#desCats table.dgrid')[0].querySelectorAll('tr.gr td.clk')].find(td=>!/^-/.test(td.textContent));const kk=cc.dataset.dgo.split('|');const kp=kk[1]+'›'+kk[2];DB.prev[kp]=0.01;render();const over=!!document.querySelector('#desCats td.over');delete DB.prev[kp];render();
    const c=document.querySelector('#desCats td.clk[data-dgo]');const dg=c.dataset.dgo;c.click();const foiExt=document.querySelector('#tab-ext').classList.contains('on')&&$('#fCat').vals.includes(dg.split('|')[1]);limpaFiltros();document.querySelector('[data-tab="des"]').click();
    return {ok:cats.length>0&&abertas&&msel&&k.includes('Saídas')&&getComputedStyle(document.querySelector('#desKpis .kpi')).textAlign==='center'&&fechou&&ok0&&over&&foiExt,abertas,msel,fechou,ok0,over,foiExt,dg}});
  t('D94','primeiro mês do ano das Despesas escolhido nas Definições; Extratos sem colunas Data valor e Saldo',await ev(()=>new Promise(ok=>{window.postMessage({tipo:'fp-mes1',mes:8},'*');setTimeout(()=>{const h=document.querySelector('#desCats table.dgrid thead th:nth-child(2)').textContent;window.postMessage({tipo:'fp-mes1',mes:0},'*');
    setTimeout(()=>{const h2=document.querySelector('#desCats table.dgrid thead th:nth-child(2)').textContent;const cols=EXT_COLS.map(c=>c[0]);ok(h==='SET/26'&&h2==='JAN/26'&&!cols.includes('Data valor')&&!cols.includes('Saldo'))},80)},80)})));
  t('D61','Despesas: categorias abertas por defeito (abrem/fecham), mês escolhido destacado, previsão bloqueada (edita-se na aba Previsões), valor acima da previsão a vermelho, clique abre os Extratos filtrados',x61.ok,x61);
  console.log('v0.8m');
  const x95=await ev(()=>new Promise(ok=>{window.postMessage({tipo:'fp-mes1',mes:8},'*');setTimeout(()=>{P.m='ano';P.d=new Date(2026,9,15);perLabel();render();
    const [a,b]=range();const lbl=document.querySelector('#perLbl')?document.querySelector('#perLbl').textContent:fpPer.estado().anoTxt;const g=mesesGraf();
    window.postMessage({tipo:'fp-mes1',mes:0},'*');setTimeout(()=>{P.m='mes';P.d=new Date(2026,8,1);perLabel();render();ok({ok:a==='2026-09-01'&&b==='2027-08-31'&&/Set 2026 – Ago 2027/.test(lbl)&&g[0][0]===2026&&g[0][1]===8&&g.length===12,a,b,lbl,g0:g[0]})},80)},80)}));
  t('D95','ano começa no primeiro mês das Definições: "Set 2026 – Ago 2027", contas e gráficos do Início seguem esse ano',x95.ok,x95);
  const x96=await ev(()=>{document.querySelector('[data-tab="des"]').click();render();
    const tt=document.querySelector('#desCats table.dgrid tr.gc td.clk[data-dgo^="ANO|"]');const c=tt&&tt.dataset.dgo.split('|')[1];tt.click();const foi=document.querySelector('#tab-ext').classList.contains('on')&&P.m==='ano'&&$('#fCat').vals.includes(c);limpaFiltros();P.m='mes';P.d=new Date(2026,8,1);perLabel();
    document.querySelector('[data-tab="des"]').click();DES.edit=true;render();const ed=document.querySelector('#desCats');const semVal=!ed.querySelector('.dgrid')&&!/€/.test(ed.textContent)&&!!ed.querySelector('[data-rso]')&&!!ed.querySelector('[data-rde]')&&!!ed.querySelector('[data-corq]');
    const n=DB.cats[0].nome;ed.querySelector('[data-corq]').click();const pop=!document.querySelector('#corPop').hidden;document.querySelector('#corPop [data-corset]').click();const cor=!!(DB.corCat||{})[n];DES.edit=false;
    COR.linha=1;COR.caixa=1;render();go('ext');render();const m=DB.mov.find(x=>x.cat===n&&!x.parts);const tr=m&&document.querySelector(`#extTable tr[data-id="${m.id}"]`);const pint=!!tr&&/--tl/.test(tr.getAttribute('style')||'')&&/color-mix/.test(tr.querySelector('select[data-f="cat"]').getAttribute('style')||'');
    const dsc=tr&&tr.querySelector('td.desc');const cs=dsc&&getComputedStyle(dsc);const linha=!!cs&&cs.whiteSpace==='nowrap'&&cs.textOverflow==='ellipsis'&&cs.verticalAlign==='middle'&&!!dsc.title;
    delete DB.corCat[n];COR.linha=0;go('prev');render();const pv=!!document.querySelector('#prevDes input.pv[data-pv]');go('des');render();
    return {ok:foi&&semVal&&pop&&cor&&pint&&linha&&pv,foi,semVal,pop,cor,pint,linha,pv}});
  t('D96','Despesas: total abre os Extratos do ano; Editar sem valores (cor, 📌 Só este movimento, ↪ Ao mudar a partir desta); cores leves nos Extratos; descrição numa linha; previsões na aba Previsões',x96.ok,x96);
  console.log('v0.9a');
  const x97=await ev(()=>{const base=DB.tiposDesp.map(t=>t.nome).join('|')==='Fixas essenciais|Fixas não essenciais|Variáveis essenciais|Variáveis não essenciais|Extras'&&DB.refTipo['Casa›Renda']==='fe';
    document.querySelector('[data-tab="des"]').click();DES.edit=true;render();const sel=document.querySelector('#desCats select[data-rtipo]');const ct=document.querySelector('#desCats select[data-ctipo]');
    const ci=+ct.dataset.ctipo,c=DB.cats[ci];ct.value='ex';ct.dispatchEvent(new Event('change',{bubbles:true}));const todas=c.refs.every(r=>DB.refTipo[c.nome+'›'+r]==='ex');
    const foraSem=[...document.querySelectorAll('#desCats details.cat')].filter(d=>eFora(d.dataset.c)).every(d=>!d.querySelector('[data-rtipo]'));
    const m=DB.mov.find(x=>x.valor<0&&x.cat&&x.ref&&!eFora(x.cat));const k0=m.cat+'›'+m.ref;DB.refTipo[k0]='vn';DES.edit=false;DES.grp='tipo';render();
    const gs=[...document.querySelectorAll('#desCats table.dgrid')[0].querySelectorAll('tr.gc')].map(x=>x.textContent);const grp=gs.some(x=>/Variáveis não essenciais/.test(x));
    DES.grp='cat';document.querySelector('[data-tab="home"]').click();render();const dn=/Extras/.test(document.querySelector('#homeDonutTipo').textContent);
    fpTipos.grava(fpTipos.lista().filter(t=>t.id!=='vn'),{vn:'ve'});const remap=DB.refTipo[k0]==='ve'&&!DB.tiposDesp.some(t=>t.id==='vn');
    const cn=DB.cats[0].nome;renomeiaCat(0,'CasaX');const ren=DB.refTipo['CasaX›Renda']!=null||!DB.cats[0].refs.includes('Renda');renomeiaCat(0,cn);
    DB.tiposDesp=TIPOS_BASE.map(([id,nome,cor])=>({id,nome,cor}));render();
    return {ok:base&&!!sel&&todas&&foraSem&&grp&&dn&&remap&&ren,base,sel:!!sel,todas,foraSem,grp,dn,remap,ren}});
  t('D97','tipos de despesa por referência (5 base, sugeridos nas referências base), "aplicar a todas" no Editar, agrupar a grelha por tipo, caixa no Início, apagar passa as referências para outro tipo',x97.ok,x97);
  const x62=await ev(()=>{document.querySelector('[data-tab="ext"]').click();limpaFiltros();render();const m=DB.mov.find(x=>x.partes&&x.partes.length);SPOPEN.add(m.id);render();
    const inp=document.querySelector(`#extTable [data-pobs="${m.id}#0"]`);inp.value='Nota X';inp.dispatchEvent(new Event('change',{bubbles:true}));
    const tx=document.querySelector('#tab-ext').textContent;return {ok:m.partes[0].obs==='Nota X'&&!/Suportados:/.test(tx)&&!/Total \(filtrado\)/.test(tx)&&!!document.querySelector('#extTable tr.fim')&&!document.querySelector('#spRows [data-spo][placeholder*="ex."]')&&!/ex\.: Eletricidade/.test(document.body.innerHTML)}});
  t('D62','Extratos: sem "Suportados", sem total no fundo (barra cinzenta), observações editáveis nas linhas divididas',x62.ok,x62);
  const x63=await ev(()=>{const f=document.querySelector('#fCat');f.value=['Alimentação','Lazer'].join('\u0001');render();const ids=[...document.querySelectorAll('#extTable tbody tr[data-id]')].map(tr=>DB.mov.find(x=>x.id===tr.dataset.id));
    const ok=ids.length>0&&ids.every(m=>(m.partes&&m.partes.length?m.partes.some(p=>['Alimentação','Lazer'].includes(p.cat)):['Alimentação','Lazer'].includes(m.cat)))&&ids.some(m=>m.cat==='Alimentação')&&f.classList.contains('on');
    f.querySelector('.msb').click();const cb=f.querySelectorAll('.msl input[type=checkbox]').length;f.querySelector('.msb').click();limpaFiltros();render();return {ok:ok&&cb>2&&!f.value,n:ids.length,cb}});
  t('D63','filtros Categoria/Referência/Quem é/Banco com multiseleção',x63.ok,x63);

  console.log('v0.7t');
  const y64=await ev(()=>{P.m='mes';P.d=new Date(2026,8,1);perLabel();document.querySelector('[data-tab="home"]').click();
    const m={id:'mR64',k:'r64',man:true,banco:'Dinheiro',conta:'',dm:'2026-09-25',dv:'2026-09-25',desc:'PAGAMENTO XPTO',valor:123,saldo:null,cat:'Rendimentos',ref:'Prémios',catSrc:'manual',det:'',obs:'',quem:'',ord:0};DB.mov.push(m);render();
    const cards=[...document.querySelectorAll('#tab-home .grid4 > .card')].length,li=[...document.querySelectorAll('#homeRend li')].map(x=>x.textContent),lt=[...document.querySelectorAll('#homeRendTipo li')].map(x=>x.textContent);
    const semRec=li.some(t=>/por confirmar/.test(t));
    DB.rend.push({id:'rT',tipo:'pon',data:m.dm,entidade:'Empresa Teste',desc:'teste',liquido:m.valor,bruto:m.valor,lk:{t:chave(m)},lkMan:{t:true}});render();
    const li2=[...document.querySelectorAll('#homeRend li')].map(x=>x.textContent);DB.rend=DB.rend.filter(r=>r.id!=='rT');DB.mov=DB.mov.filter(x=>x.id!=='mR64');render();
    return {ok:cards===4&&semRec&&lt.some(t=>/Prémios/.test(t))&&li2.some(t=>/Empresa Teste/.test(t)&&/✓/.test(t)),cards,li,lt,li2}});
  t('D64','Início: Rendimentos do extrato por entidade (✓ = com recibo) e caixa Rendimentos por tipo — 4 caixas na linha',y64.ok,y64);
  t('D65','Rendimentos: caixas como no Início e "＋ Adicionar rendimento" no Resumo anual com menu (recibo PDF | manual)',await ev(()=>{const k=document.querySelector('#renKpis .kpi');const b=document.querySelector('#renAno').closest('.card').querySelector('[data-dd="ddRend"]');if(!b||document.querySelector('#renKpis .kpi .s'))return false;b.click();const m=document.querySelector('#ddRend');const ok=!m.hidden&&m.querySelectorAll('button')[0].id==='btRec'&&m.querySelectorAll('button')[1].dataset.radd2==='rec'&&getComputedStyle(k).textAlign==='center';document.body.click();return ok&&m.hidden}));

  console.log('v0.8a');
  const z66=await ev(()=>{P.m='mes';P.d=new Date(2026,8,1);perLabel();document.querySelector('[data-tab="home"]').click();render();
    const ic=document.querySelectorAll('#homeKpis .kc').length;document.querySelector('#homeKpis [data-calc="ent"]').click();
    const aberto=!document.querySelector('#calcPan').hidden,naoNavegou=document.querySelector('#tab-home').classList.contains('on');
    const ce=CALC.ent(),se=r2(ce.b[0].it.reduce((s,m)=>s+m.valor,0)),cs=CALC.sai(),ss=r2(cs.b[0].it.reduce((s,m)=>s-m.valor,0)-cs.b[1].it.reduce((s,m)=>s+m.valor,0));
    const temFora=ce.fora.every(x=>x.mot)&&cs.fora.every(x=>x.mot);const txt=document.querySelector('#calcBody').textContent;
    document.querySelector('#calcX').click();
    return {ok:ic===4&&aberto&&naoNavegou&&Math.abs(se-ce.tot)<.005&&Math.abs(ss-cs.tot)<.005&&temFora&&/Ficaram de fora|Contam/.test(txt)&&document.querySelector('#calcPan').hidden,ic,se,tot:ce.tot,ss,st:cs.tot}});
  t('D66','🧮 nas caixas do Início abre o painel lateral "Como foi calculado" (o que conta soma o valor da caixa; o que fica de fora tem o motivo)',z66.ok,z66);
  t('D67','🧮 também em Despesas e Rendimentos; a opção nas Definições esconde o ícone',await ev(()=>{document.querySelector('[data-tab="des"]').click();const d=document.querySelectorAll('#desKpis .kc').length;document.querySelector('[data-tab="ren"]').click();const r=document.querySelectorAll('#renKpis .kc').length;document.querySelector('[data-tab="home"]').click();
    window.postMessage({tipo:'fp-calc',on:false},'*');return new Promise(ok=>setTimeout(()=>{const n=document.querySelectorAll('#homeKpis .kc').length;window.postMessage({tipo:'fp-calc',on:true},'*');setTimeout(()=>ok(d===3&&r===4&&n===0&&document.querySelectorAll('#homeKpis .kc').length===4),100)},100))}));
  t('D68a','logo ao lado do título e ícone da página',await ev(()=>!!document.querySelector('.top h1 img.logo')&&!!document.querySelector('link[rel="icon"]')));

  console.log('v0.8b');
  t('D69','tamanho padrão = 90% real (o novo 100%)',await ev(()=>getComputedStyle(document.documentElement).zoom==='0.9'||document.documentElement.style.zoom===''&&/zoom:\s*\.9/.test(document.querySelector('style').textContent)));
  t('D70','ordem dos movimentos do extrato (mais recentes/antigos primeiro)',await ev(()=>{document.querySelector('[data-tab="ext"]').click();limpaFiltros();render();const ds=()=>[...document.querySelectorAll('#extTable tbody tr[data-id]')].map(tr=>DB.mov.find(x=>x.id===tr.dataset.id).dm);
    const a=ds();window.postMessage({tipo:'fp-ordem',ordem:'asc'},'*');return new Promise(ok=>setTimeout(()=>{const b=ds();window.postMessage({tipo:'fp-ordem',ordem:''},'*');setTimeout(()=>ok(a.length>2&&a[0]>=a[a.length-1]&&b[0]<=b[b.length-1]&&a[0]!==b[0]),80)},80))}));
  const z71=await ev(()=>{const m=DB.mov.filter(x=>x.valor<0).sort((a,b)=>a.dm<b.dm?-1:1)[1];const r={id:'rb71',desc:'X',valor:5,dm:m.dm,cat:'',ref:''};abreReemb(r);
    const tit=document.querySelector('#mReemb h3').textContent;document.querySelector('#rbTodas').click();const pb=!document.querySelector('#rbPost').hidden;
    const d1=[...document.querySelectorAll('#rbList tbody tr:not(.rbparte)')].map(tr=>tr.children[0].textContent.split('/').reverse().join('-'));
    document.querySelector('#rbPost').click();const d2=[...document.querySelectorAll('#rbList tbody tr:not(.rbparte)')].map(tr=>tr.children[0].textContent.split('/').reverse().join('-'));document.querySelector('#mReemb').hidden=true;RB=null;
    return {ok:tit==='Reembolso'&&pb&&d1.length>0&&d1.every(d=>d<=m.dm)&&d1.every((d,i)=>!i||d<=d1[i-1])&&d2.every(d=>d>m.dm)&&d2.every((d,i)=>!i||d>=d2[i-1]),tit,d1,d2,dm:m.dm}});
  t('D71','Reembolso: título, "Mostrar todas" da data para trás e botão "Posteriores"',z71.ok,z71);
  t('D72','Dividir: 1.ª linha cinzenta, restantes valores e observações a branco',await ev(()=>{abreSplit(DB.mov.find(x=>x.valor<0&&!(x.partes&&x.partes.length)));const bg=q=>getComputedStyle(document.querySelector(q)).backgroundColor;const card=getComputedStyle(document.querySelector('.card')).backgroundColor;
    const ok=bg('#spRows tr:first-child [data-spv]')!==card&&bg('#spRows tr:nth-child(2) [data-spv]')===card&&bg('#spRows tr:first-child [data-spo]')===card;document.querySelector('#mSplit').hidden=true;SP=null;return ok}));

  console.log('v0.8c');
  t('D74','filtro Entradas/Saídas destacado a azul quando ativo e caixa branca',await ev(()=>{document.querySelector('[data-tab="ext"]').click();limpaFiltros();render();const f=document.querySelector('#fTipo'),card=getComputedStyle(document.querySelector('.card')).backgroundColor;
    const a=!f.classList.contains('on')&&getComputedStyle(f).backgroundColor===card;f.value='e';f.dispatchEvent(new Event('change'));const b=f.classList.contains('on');limpaFiltros();render();return a&&b}));
  const z75=await ev(()=>{const n=normaliza({mov:[{id:'a',banco:'X',conta:'',dm:'2026-01-01',dv:'2026-01-01',desc:'D',valor:-10,saldo:null,partes:[{valor:-6,cat:'',ref:'',obs:'Luz'},{valor:-4,cat:'',ref:'',obs:''}]}]});
    const mig=n.mov[0].partes[0].desc==='Luz'&&n.mov[0].partes[0].obs==='';
    const m=DB.mov.find(x=>x.partes&&x.partes.length);abreSplit(m);const th=[...document.querySelectorAll('#mSplit thead th')].map(x=>x.textContent);
    document.querySelector('#spRows tr:nth-child(1) [data-spo]').value='Descr A';document.querySelector('#spOk').click();
    SPOPEN.add(m.id);render();const tr=document.querySelector(`#extTable tr.parte[data-pid="${m.id}#0"]`);
    return {ok:mig&&th.includes('Descrição')&&!th.includes('Observações')&&m.partes[0].desc==='Descr A'&&m.partes[0].obs==='Nota X'&&/Descr A/.test(tr.textContent)&&tr.querySelector('[data-pobs]').value==='Nota X',th,p:m.partes[0]}});
  t('D75','linhas divididas: Descrição na janela Dividir, Observações na tabela (separadas)',z75.ok,z75);
  t('D76','Regras especiais com nome e tipo; "Só este movimento" e "Transferências" já criadas; adicionar/tirar referências',await ev(()=>{document.querySelector('#btRegras').click();document.querySelector('#mRegras [data-mtab="mEsp"]').click();const vis=!document.querySelector('#mEsp').hidden;
    const nomes=[...document.querySelectorAll('#espList .espn')].map(x=>x.value);const tr=DB.esp.find(e=>e.nome==='Transferências');
    const w=document.querySelector('#espList .espc'),c=w.querySelector('[data-eac]');c.value='Lazer';c.dispatchEvent(new Event('change',{bubbles:true}));const r=w.querySelector('[data-ear]');r.value='Jogos';w.querySelector('[data-eadd]').click();
    const ok1=soMov('Lazer','Jogos');document.querySelector('#espList .espc [data-erdel$="Lazer›Jogos"]').click();const ok2=!soMov('Lazer','Jogos');
    const n0=DB.esp.length;document.querySelector('#espNova').click();const ok3=DB.esp.length===n0+1;DB.esp.pop();document.querySelector('#mEsp').hidden=true;
    return vis&&nomes.includes('Só este movimento')&&nomes.includes('Transferências')&&tr.tipo==='de'&&tr.refs.length===3&&ok1&&ok2&&ok3}));
  t('D77','linhas com Transferência / rec / pag: ao mudar a categoria ou referência não pergunta se quer criar regra',await ev(()=>{document.querySelector('[data-tab="ext"]').click();limpaFiltros();render();
    const m=DB.mov.find(x=>!x.man&&!(x.partes&&x.partes.length));m.cat='Por tratar';m.ref='Transferência rec';render();
    const tr=()=>document.querySelector(`#extTable tr[data-id="${m.id}"]`);const sc=tr().querySelector('[data-f="cat"]');sc.value='Casa';sc.dispatchEvent(new Event('change',{bubbles:true}));
    const sr=tr().querySelector('[data-f="ref"]');sr.value='Água';sr.dispatchEvent(new Event('change',{bubbles:true}));const semPergunta=document.querySelector('#mNovaRegra').hidden;
    const sr2=tr().querySelector('[data-f="ref"]');sr2.value='Internet';sr2.dispatchEvent(new Event('change',{bubbles:true}));const pergunta=!document.querySelector('#mNovaRegra').hidden;document.querySelector('#mNovaRegra').hidden=true;
    return semPergunta&&pergunta&&m.cat==='Casa'&&m.catSrc==='manual'}));

  t('D78','reembolso ligado mostra na Descrição o nome da despesa original (e pesquisa por ele)',await ev(()=>{document.querySelector('[data-tab="ext"]').click();limpaFiltros();render();const m=DB.mov.find(x=>x.id==='mRb');const o=mapaChaves().get(m.reemb);
    const tr=document.querySelector('#extTable tr[data-id="mRb"]');const ok1=!!tr&&tr.querySelector('td.desc').textContent.includes(nomeMov(o))&&/DEVOLUCAO AMIGO/.test(tr.querySelector('td.desc').title);
    document.querySelector('#fQ').value=o.desc.split(' ')[0];render();const ok2=!!document.querySelector('#extTable tr[data-id="mRb"]');limpaFiltros();render();return ok1&&ok2}));

  const z83=await ev(()=>{const n0=DB.mov.length;for(let k=0;k<350;k++)DB.mov.push({id:'big'+k,k:'big'+k,man:true,banco:'Dinheiro',conta:'',dm:'2026-09-'+String(1+k%28).padStart(2,'0'),dv:'2026-09-01',desc:'MOV '+k,valor:-1,saldo:null,cat:'',ref:'',catSrc:'',det:'',obs:'',quem:'',ord:k,c:k});
    document.querySelector('[data-tab="ext"]').click();limpaFiltros();const t0=performance.now();render();const ms=Math.round(performance.now()-t0);
    const a=document.querySelectorAll('#extTable tr[data-id]').length,sent=!!document.querySelector('#extMais');extMais();const b=document.querySelectorAll('#extTable tr[data-id]').length;
    const sa=document.querySelector('#selAll');sa.checked=true;sa.dispatchEvent(new Event('change',{bubbles:true}));const sel=SEL.size;sa.checked=false;sa.dispatchEvent(new Event('change',{bubbles:true}));
    const alvo=DB.mov.find(x=>x.id==='big5');irMovimento(chave(alvo));const vis=!!document.querySelector('#extTable tr[data-id="big5"]');
    DB.mov=DB.mov.filter(x=>!String(x.id).startsWith('big'));limpaFiltros();render();return {ok:a===100&&sent&&b===200&&sel>=350&&vis&&DB.mov.length===n0,a,b,sel,ms,vis}});
  t('D83','Extratos: mostra 100 linhas de cada vez (mais 100 ao descer); selecionar tudo e ir para um movimento funcionam com todas',z83.ok,z83);
  t('D84','só se desenha a aba aberta; as outras desenham-se ao abrir',await ev(()=>{document.querySelector('[data-tab="ext"]').click();render();const v=RV;const d=DESENHADA.home!==v;document.querySelector('[data-tab="home"]').click();return d&&DESENHADA.home===RV}));

  t('D88','ao sair dos Extratos volta às 100 primeiras linhas',await ev(()=>{for(let k=0;k<250;k++)DB.mov.push({id:'big'+k,k:'big'+k,man:true,banco:'Dinheiro',conta:'',dm:'2026-09-10',dv:'2026-09-10',desc:'MOV '+k,valor:-1,saldo:null,cat:'',ref:'',catSrc:'',det:'',obs:'',quem:'',ord:k,c:k});
    document.querySelector('[data-tab="ext"]').click();limpaFiltros();render();extMais();const a=document.querySelectorAll('#extTable tr[data-id]').length;document.querySelector('[data-tab="home"]').click();document.querySelector('[data-tab="ext"]').click();
    const b=document.querySelectorAll('#extTable tr[data-id]').length;DB.mov=DB.mov.filter(x=>!String(x.id).startsWith('big'));render();return a===200&&b===100}));

  console.log('Início');
  await go('home');
  t('D34','Início não conta categorias fora das contas, exceto entradas de Rendimentos',await ev(()=>!contaInicio({valor:-10,cat:'Por tratar',ref:'x'})&&!contaInicio({valor:10,cat:'Por tratar'})&&!contaInicio({valor:10,cat:'Banco',ref:'x'})&&!contaInicio({valor:-10,cat:'Investimentos'})&&contaInicio({valor:-10,cat:'Alimentação'})&&contaInicio({valor:10,cat:'Rendimentos'})&&!contaInicio({valor:-10,cat:'Rendimentos'})&&contaInicio({valor:-10,cat:''})));
  t('D35','donut de despesas do Início sem categorias fora das contas',await ev(()=>{const m=DB.mov.find(x=>x.valor<0);m.cat='Por tratar';m.ref='Transferência pag';render();return ![...document.querySelectorAll('#homeDonut li')].some(li=>/Por tratar/.test(li.textContent))}));
  t('D30','caixa de rendimentos existe e despesas são clicáveis',await ev(()=>!!document.querySelector('#homeRend')&&!!document.querySelector('#homeDonut li.clk')));
  t('D36','"Por categorizar" mostra todas as descrições (sem limite)',await ev(()=>{const n=new Set(DB.mov.filter(x=>{const [a,b]=range();return x.dm>=a&&x.dm<=b&&isUnc(x)}).map(x=>norm(x.desc))).size;return document.querySelectorAll('#homeUnc tbody tr').length===n}));
  t('D37','caixas do Início sem texto (só ao passar o rato) e Entradas/Saídas clicáveis',await ev(()=>!document.querySelector('#homeKpis .kpi .s')&&document.querySelector('#homeKpis .kpi').title.length>0&&!!document.querySelector('#homeKpis [data-gotipo="e"]')));
  await ev(()=>document.querySelector('#homeKpis [data-gotipo="s"]').click());
  t('D38','clicar em Saídas abre os Extratos com o filtro "Só saídas"',await ev(()=>document.querySelector('#tab-ext').classList.contains('on')&&document.querySelector('#fTipo').value==='s'));
  t('D46','milhares sempre com espaço (1 234,56 €)',await ev(()=>/^1\s234,56\s€$/.test(E(1234.56))&&/^-4\s038,06\s€$/.test(E(-4038.06))));
  await ev(()=>{document.querySelector('[data-tab="ext"]').click()});
  const d08=await ev(()=>{const h=[...document.querySelectorAll('#extHead th')],tr=document.querySelector('#extTable tbody tr:not(.parte)'),c=[...tr.children];return {n:[h.length,c.length],L:h.map((x,i)=>Math.round(x.getBoundingClientRect().left)+'/'+Math.round(c[i].getBoundingClientRect().left)).join(' '),sl:[document.querySelector('#extHead').scrollLeft,document.querySelector('#extTable').scrollLeft,document.querySelector('#extHead').clientWidth,document.querySelector('#extTable').clientWidth],ok:h.length===c.length&&h.every((x,i)=>Math.abs(x.getBoundingClientRect().left-c[i].getBoundingClientRect().left)<1.5),ov:getComputedStyle(document.documentElement).overflowY}});
  t('D08c','títulos da tabela na barra fixa, alinhados com as colunas, e barra de scroll reservada',d08.ok&&d08.ov==='scroll',d08);
  t('D08b','tabela de movimentos com larguras de coluna fixas',await ev(()=>!!document.querySelector('#extTable table.tfix colgroup')));
  await ev(()=>document.querySelector('[data-tab="home"]').click());
  t('D31','"Por categorizar" mostra só as mais frequentes (com ⚡)',await ev(()=>!document.querySelector('#uncVista')&&UNCV==='freq'));
  t('D32','caixa "Despesas por referência" e gráfico com opção Detalhado',await ev(()=>!!document.querySelector('#homeDonutRef')&&document.querySelectorAll('#barsVista button').length===2));
  t('D33','gráfico de entradas/saídas mostra sempre os 12 meses do ano',await ev(()=>mesesGraf().length===12));

  console.log('Estado');
  await go('ext');await p.fill('#fQ','NETFLIX');await p.selectOption('#fTipo','s');await p.waitForTimeout(100);
  await p.reload();await p.waitForTimeout(500);
  t('D45','ao atualizar mantém aba, pesquisa e filtros',await ev(()=>document.querySelector('#tab-ext').classList.contains('on')&&document.querySelector('#fQ').value==='NETFLIX'&&document.querySelector('#fTipo').value==='s'));

  console.log('Millennium');
  await go('ext');const n90=await ev(()=>DB.mov.length);
  await p.setInputFiles('#fExt',path.join(FX,'millennium_ordem_teste.xlsx'));await p.waitForTimeout(900);const res90=await ev(()=>document.querySelector('#impRes').textContent);
  await p.setInputFiles('#fExt',path.join(FX,'millennium_cartao_teste.xlsx'));await p.waitForTimeout(900);
  const z90=await ev(([n0,r0])=>{const o=DB.mov.filter(m=>m.banco==='Millennium'),c=DB.mov.filter(m=>m.banco==='Millennium Cartão'),res=document.querySelector('#impRes').textContent;
    const caf=o.find(m=>/CAFE/.test(m.desc)),sup=c.filter(m=>/SUPERMERCADO/.test(m.desc)),loja=c.filter(m=>m.desc==='LOJA ONLINE TESTE');
    const dbg={pag:DB.mov.filter(m=>/PAGAMENTO CARTAO/.test(m.desc)).map(m=>m.cat+'›'+m.ref),lev:o.find(m=>/LEV ATM/.test(m.desc)).ref,det:caf.det};
    return {dbg,ok:o.length===5&&c.length===5&&o[0].conta==='11112222333'&&caf.desc==='CAFE DO TESTE PORTO'&&/Compra · cartão 1234/.test(caf.det)&&sup.some(m=>m.valor===-20.1)&&sup.some(m=>m.valor===2.5)&&loja.length===2
      &&DB.mov.filter(m=>/PAGAMENTO CARTAO/.test(m.desc)).every(m=>m.cat==='Banco'&&m.ref==='Troca entre contas')&&o.find(m=>/LEV ATM/.test(m.desc)).ref==='Levantamentos'&&o.find(m=>/EMPRESA FICTICIA/.test(m.desc)).desc==='TRF EMPRESA FICTICIA LDA'&&/saldo final 1\s000,50\s€ ✓/.test(r0),o:o.map(m=>[m.desc,m.valor]),c:c.map(m=>[m.desc,m.valor]),r0}},[n90,res90]);
  t('D90','Millennium BCP (Excel): conta à ordem e conta cartão (sinais trocados), prefixos limpos, repetidos no mesmo dia mantidos, pagamento do cartão entre contas',z90.ok,z90);
  await p.setInputFiles('#fExt',path.join(FX,'millennium_cartao_teste.xlsx'));await p.waitForTimeout(900);
  t('D91','reimportar o cartão (sem saldo) não duplica nem perde movimentos iguais',await ev(()=>DB.mov.filter(m=>m.banco==='Millennium Cartão').length===5));

  await p.setInputFiles('#fExt',path.join(FX,'bpi_teste.xlsx'));await p.waitForTimeout(900);
  const z93=await ev(()=>{const b=DB.mov.filter(m=>m.banco==='BPI'),res=document.querySelector('#impRes').textContent;const pd=b.find(m=>/PADARIA/.test(m.desc));
    return {ok:b.length===4&&b[0].conta==='0-1234567.000.001'&&pd.desc==='PADARIA TESTE PORTO'&&/Compra 17\/09 · cartão 1111111/.test(pd.det)&&b.some(m=>m.desc==='TRF EMPRESA FICTICIA SA'&&m.valor===1000)&&b.find(m=>/^LEV ATM/.test(m.desc)).ref==='Levantamentos'&&b.some(m=>m.desc==='SEGURADORA TESTE SA 123456')&&/saldo final 1\s050,40\s€ ✓/.test(res),b:b.map(m=>[m.desc,m.valor,m.det]),res}});
  t('D93','BPI (Excel do BPI Net): conta com saldo validado, prefixos limpos (compra/levantamento com data e cartão, transferências, débito direto)',z93.ok,z93);

  console.log('Página principal');
  await p.goto(U+'/index.html');await p.waitForTimeout(300);
  const tabs=await ev(()=>[...document.querySelectorAll('nav a')].map(a=>a.textContent));
  t('D40','Finanças é o primeiro separador',tabs[0]==='Finanças',tabs);
  t('D41','separadores externos nunca recebem sessão/tema (data-ext)',await ev(()=>{location.hash='#biblia';return new Promise(r=>setTimeout(()=>r(!!document.querySelector('iframe[data-ext]')&&/:not\(\[data-ext\]\)/.test(document.body.innerHTML)),300))}));
  t('D42','menu (avatar ▾) com Definições, Plano, Onboarding e modo escuro',await ev(()=>!!document.querySelector('#btMenu')&&['[data-set="tema"]','#miPlano','#miOnb','#miTema'].every(q=>document.querySelector(q))));
  t('D44','versão no canto do menu da conta (sem subtítulo nas Finanças)',await ev(()=>{document.querySelector('#btMenu').click();const v=document.querySelector('#mVer').textContent;document.querySelector('#btMenu').click();const f=document.querySelector('iframe[data-id="financas"]').contentDocument;return /^v0\./.test(v)&&!f.querySelector('.top p')}));
  t('D68','Definições com menu vertical e tamanho fixo; "Geral" tem tema, tamanho, idioma, ordem dos movimentos e a opção do ícone 🧮',await ev(()=>{document.querySelector('[data-set="tema"]').click();const nav=document.querySelector('#setNav'),b=nav.querySelector('button'),box=document.querySelector('#mSet .big'),h1=box.offsetHeight;
    const g=document.querySelector('section[data-s="tema"]');const ok1=getComputedStyle(nav).flexDirection==='column'&&/Geral/.test(b.textContent)&&!g.hidden&&['#gTema','#gZoom','#optCalc','#gOrdem','select'].every(q=>g.querySelector(q))&&!nav.querySelector('[data-s="idioma"]');
    nav.querySelector('[data-s="onb"]').click();const h2=box.offsetHeight;document.querySelector('#mSet').hidden=true;
    const z=[...document.querySelectorAll('#gZoom .opt')].map(x=>x.textContent);return ok1&&h1===h2&&z.join('|')==='80%|90%|100% (padrão)|110%|120%'&&!!document.querySelector('link[rel="icon"]')}));
  const z73=await ev(()=>new Promise(ok=>{location.hash='#financas';setTimeout(()=>{try{const f=document.querySelector('iframe[data-id="financas"]'),w=f.contentWindow,fp=document.querySelector('#fPer');
    const vis=!fp.hidden,topHidden=getComputedStyle(w.document.querySelector('.top')).display==='none',lbl=document.querySelector('#pLbl').textContent===w.document.querySelector('#perLbl').textContent;
    document.querySelector('#pMode [data-m="ano"]').click();FPPer.pinta();const ano=w.fpPer.estado().m==='ano'&&document.querySelector('#pLbl').textContent===String(w.fpPer.estado().ano);
    document.querySelector('#pNav [data-d="-1"]').click();const y0=w.fpPer.estado().ano;document.querySelector('#pHoje').click();const hj=w.fpPer.estado().ano===new Date().getFullYear()&&y0===new Date().getFullYear()-1&&document.querySelector('#pHoje').classList.contains('atual');
    document.querySelector('#pMode [data-m="mes"]').click();document.querySelector('#pLbl').click();const cal=!document.querySelector('#pCal').hidden;document.querySelector('#pCal [data-cmes="5"]').click();const jun=w.fpPer.estado().m==='mes'&&w.fpPer.estado().mes===5;
    const sync=document.querySelector('#pSync').textContent.length>0;
    location.hash='#simulador';setTimeout(()=>{const esc=document.querySelector('#fPer').hidden;location.hash='#financas';ok({ok:vis&&topHidden&&lbl&&ano&&hj&&cal&&jun&&sync&&esc,vis,topHidden,lbl,ano,hj,cal,jun,sync,esc})},300)}catch(e){ok({ok:false,err:String(e)})}},600)}));
  t('D73','período (Mês/Ano/Intervalo, data, calendário, Guardado) e botão "Hoje" na barra de cima; título das Finanças sai; escondidos noutros separadores',z73.ok,z73);
  t('D79','Enviar sugestão: formulário (tipo, texto, email opcional, armadilha anti-robôs)',await ev(()=>['#sgTipo','#sgTxt','#sgSite','#sgMail','#sgEnviar'].every(q=>document.querySelector(q))));
  const z43=await ev(()=>new Promise(ok=>{FPOnb.abre();setTimeout(()=>{const t=document.querySelector('#tour');const vis=!t.hidden;const n=FPOnb.S.length;const g=new Set(FPOnb.S.map(x=>x.g));
    ['a','b','c'].forEach(()=>document.querySelector('#tourBub [data-tv="seg"]').click());setTimeout(()=>{const spot=document.querySelector('#tourSpot');const destaca=!spot.classList.contains('centro')&&spot.offsetWidth>20;
      document.querySelector('#tourBub [data-tv="sair"]').click();FPOnb.abre('ext');setTimeout(()=>{const só=/\/ (\d+)/.exec(document.querySelector('#tourBub .n').textContent)[1]*1===FPOnb.S.filter(x=>x.g==='ext').length;const naAba=document.querySelector('iframe[data-id="financas"]').contentDocument.querySelector('#tab-ext').classList.contains('on');FPOnb.fecha();
      ok({ok:vis&&n>=20&&['home','ext','ren','des','barra'].every(x=>g.has(x))&&destaca&&só&&naAba&&!!document.querySelector('#setOnbG [data-og="ren"]'),vis,n,destaca,só,naAba})},900)},700)},300)}));
  t('D85','sinais de perguntas/sugestões novas escondidos para quem não é admin; visita guiada sem etiquetas das abas',await ev(()=>['#bdgMenu','#bdgFaq','#bdgSug'].every(q=>document.querySelector(q)&&document.querySelector(q).hidden)&&!FPOnb.S.some(()=>false)&&(()=>{FPOnb.abre();const ok=!document.querySelector('#tourBub .grp2');FPOnb.fecha();return ok})()));
  const z87=await ev(()=>new Promise(ok=>{FPOnb.abre();setTimeout(()=>{const t1=document.querySelector('#tourBub h4').textContent,sel=!!document.querySelector('#tourIdioma');document.querySelector('#tourBub [data-tv="seg"]').click();
    setTimeout(()=>{const t2=document.querySelector('#tourBub h4').textContent;document.querySelector('#tourTema [data-tt="dark"]').click();const esc=document.documentElement.dataset.theme==='dark';document.querySelector('#tourTema [data-tt=""]').click();
      document.querySelector('#tourBub [data-tv="seg"]').click();setTimeout(()=>{const t3=document.querySelector('#tourBub h4').textContent;const lh=parseFloat(getComputedStyle(document.querySelector('#tourBub p')).lineHeight)/parseFloat(getComputedStyle(document.querySelector('#tourBub p')).fontSize);FPOnb.fecha();
      ok({ok:/Idioma/.test(t1)&&sel&&/Tema/.test(t2)&&esc&&/Bem-vindo/.test(t3)&&lh>=1.7,t1,t2,t3,lh})},300)},300)},300)}));
  t('D87','visita guiada começa por Idioma e Tema (claro/escuro) e depois Bem-vindo; texto mais espaçado',z87.ok,z87);
  t('D89','sugestões recebidas numa aba própria, escondida para quem não é admin',await ev(()=>{document.querySelector('[data-set="sugestao"]').click();return new Promise(ok=>setTimeout(()=>{const r=document.querySelector('#sgTabs').hidden&&!document.querySelector('#sgEnv').hidden&&!!document.querySelector('#sgTabs [data-st="rec"]');document.querySelector('#mSet').hidden=true;ok(r)},50))}));
  t('D43','visita guiada nos botões reais, por aba (completa ou só de uma página)',z43.ok,z43);
  t('D80','Novidades: não aparecem na 1.ª visita; aparecem numa versão nova com Novas funcionalidades e Alterações, sem scroll',await ev(()=>{const vis0=document.querySelector('#mNov').hidden;FPNov.mostra('0.8a');const m=document.querySelector('#mNov .box');const ok=!document.querySelector('#mNov').hidden&&document.querySelectorAll('#novN li').length>0&&document.querySelectorAll('#novA li').length>0&&m.scrollHeight<=m.clientHeight+2&&m.getBoundingClientRect().height<=innerHeight;document.querySelector('#novOk').click();return vis0&&ok&&FPNov.cmp('0.8a','0.8g')<0&&FPNov.cmp('0.10a','0.9z')>0}));
  t('D81','Novidades: a versão mais recente das notas = versão da aplicação',await ev(()=>NOVIDADES[0].v===document.querySelector('iframe[data-id="financas"]').contentWindow.FP_VERSAO));
  await ev(()=>{document.querySelector('[data-set="tema"]').click();document.querySelector('#setNav [data-s="tipos"]').click()});await p.waitForTimeout(150);
  const n98=await ev(()=>document.querySelectorAll('#tiposL .tprow').length);await ev(()=>document.querySelector('#tipoAdd').click());await p.waitForTimeout(150);
  const z98=await ev(n=>{const w=document.querySelector('iframe[data-id="financas"]').contentWindow;const n2=w.fpTipos.lista().length,r=document.querySelectorAll('#tiposL .tprow').length;w.fpTipos.grava(w.fpTipos.lista().slice(0,n),{});document.querySelector('#mSet').hidden=true;return {ok:n>=5&&n2===n+1&&r===n+1,n,n2,r}},n98);
  t('D98','Definições › Tipos de despesa: lista os tipos das Finanças e permite criar um novo',z98.ok,z98);
  t('D82','FAQs: pesquisa, filtro por labels, perguntar e aba de gestão (só admin)',await ev(()=>['#fqQ','#fqLb','#fqList','#fqNova','#fqEnviar','#fqTabs [data-ft="minhas"]'].every(q=>document.querySelector(q))&&document.querySelector('#fqTabs [data-ft="adm"]').hidden&&/FAQs/.test(document.querySelector('#setNav [data-s="ajuda"]').textContent)));

  t('D99','sem erros de JavaScript',erros.length===0,erros);
  await b.close();srv.close();
  console.log(`\n${ok} ok · ${falhas.length} falha(s)`);if(falhas.length){console.log('FALHAS:\n - '+falhas.join('\n - '));process.exit(1)}
})().catch(e=>{console.error(e);srv.close();process.exit(2)});
